//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SherzadSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountEntry
    {
        public int Aid { get; set; }
        public int JournalId { get; set; }
        public int EmpId { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual JournalEntry JournalEntry { get; set; }
    }
}
