//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SherzadSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Bid { get; set; }
        public string BookName { get; set; }
        public string BookAuthor { get; set; }
        public int PublishYear { get; set; }
        public string BookFile { get; set; }
        public string PublishingIndustry { get; set; }
        public Nullable<int> Cate_id { get; set; }
    
        public virtual BookCategories BookCategories { get; set; }
    }
}
