//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SherzadSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShirzadSystem : DbContext
    {
        public ShirzadSystem()
            : base(Defaults.ConnectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountEntry> AccountEntry { get; set; }
        public virtual DbSet<BookCategories> BookCategories { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<ERCodes> ERCodes { get; set; }
        public virtual DbSet<Faculties> Faculties { get; set; }
        public virtual DbSet<JournalEntry> JournalEntry { get; set; }
        public virtual DbSet<Literature> Literature { get; set; }
        public virtual DbSet<Monograph> Monograph { get; set; }
        public virtual DbSet<PersonInformation> PersonInformation { get; set; }
        public virtual DbSet<Tills> Tills { get; set; }
        public virtual DbSet<Universities> Universities { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
