//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SherzadSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Literature
    {
        public int Lid { get; set; }
        public int UniqueId { get; set; }
        public string LiteratureName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string remarks { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal TotalRecived { get; set; }
        public int Person { get; set; }
    
        public virtual PersonInformation PersonInformation { get; set; }
    }
}
